# Generated by Django 2.0.5 on 2018-05-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0003_auto_20180524_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=500, verbose_name='video_url')),
                ('description', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('tags', models.ManyToManyField(related_name='videos', to='news.Tags')),
            ],
        ),
    ]
