# Generated by Django 2.0.5 on 2018-05-24 10:10

from django.db import migrations

def add_languages(apps, schema_editor):
    Language= apps.get_model('news','Language')
    english= Language()
    english.name='English'
    english.code='en'
    english.save()

    hindi = Language()
    hindi.name='हिंदी'
    hindi.code='hi'
    hindi.save()

    gujarati = Language()
    gujarati.name='ગુજરાતી'
    gujarati.code='gu'
    gujarati.save()

    marathi = Language()
    marathi.name='मराठी'
    marathi.code='mr'
    marathi.save()




class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_content'),
    ]

    operations = [
        migrations.RunPython(add_languages)
    ]
